### PR TITLE
nbrx: set minimum buffer size for input to rx_filter

### LINKED ISSUE #1233: Setting the filter width too narrow causes DSP to hang
Fedora 38 with gqrx-2.15.9-7.fc38.x86_64. (However, I was able to reproduce the same issue with latest Gqrx master.)

DSP hangs after setting the filter width too narrow using Ctrl + mouse wheel. See the following screencast:

[filter_width_hang.webm](https://user-images.githubusercontent.com/2339930/235373018-cec9cc1c-27b9-4a74-8df3-0649488a964e.webm)

This gets printed on stdout:
```
block_executor :error: sched: <block fir_filter_blk<IN_T,OUT_T,TAP_T> (14)> is requesting more input data  than we can provide.  ninput_items_required = 11570  max_possible_items_available = 8191  If this is a filter, consider reducing the number of taps.
```

### PR DESCRIPTION
**Pull request by willcode**
Width of rx_filter can be adjusted at run time, so the input buffer (the output buffer of nb) needs to be large enough for the longest history required by the filter (Narrow/Sharp). This setting may not be reliable for GR prior to v3.10.7.0.

Fixes #1233

### CODE REVIEW

File: src/receivers/nbrx.cpp [hunk 1]
```diff
@@ -53,6 +53,12 @@ nbrx::nbrx(float quad_rate, float audio_rate)
     demod_am = make_rx_demod_am(PREF_QUAD_RATE, true);
     demod_amsync = make_rx_demod_amsync(PREF_QUAD_RATE, true, 0.001);
 
+    // Width of rx_filter can be adjusted at run time, so the input buffer (the
+    // output buffer of nb) needs to be large enough for the longest history
+    // required by the filter (Narrow/Sharp). This setting may not be reliable
+    // for GR prior to v3.10.7.0.
+    nb->set_min_output_buffer(32768);
```
Comment (argilo) [inline src/receivers/nbrx.cpp:60]: @willcode I removed the `sizeof(gr_complex)` here, because `set_min_output_buffer` takes the number of items. I also decreased the value so that we don't end up with higher latency than required. The largest number of taps I could generate (upper sideband, sharp filter, Ctrl+scroll wheel to narrow to 100 Hz) was 23127, so I chose the next power of 2.
